# action.yml
name: QAEnv Tests
on: push
  # schedule:
  #   - cron: '0 8 1-31 * *'

jobs:

  install:
    runs-on: ubuntu-22.04
    container:
      image: cypress/included:12.17.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          # Disable running of tests within install job
          working-directory: ui-test
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: dist


  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      # don't fail the entire matrix on failure
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          working-directory: ui-test
          command: npx cypress run --spec cypress/e2e/contentManager/test.cy.js --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json

      # - name: Copy test execution videos
      #   working-directory: ui-test
      #   run: |
      #     mkdir public
      #     cp -r /__w/test/test/ui-test/cypress/videos/ public/videos/

      # - name: Merge test results into one
      #   working-directory: ui-test
      #   run: npm run report:merge

      # - name: Generate HTML report
      #   working-directory: ui-test
      #   run: npm run report:generate
        
      # - name: Get current date
      #   id: date
      #   run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # - name: Deploy report page
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: /__w/test/test/ui-test/public
      #     destination_dir: qa/run-${{ steps.date.outputs.date }}/





