name: Cypress Tests
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          working-directory: ui-test
          command: npx cypress run --spec cypress/e2e/contentManager/*.cy.js --reporter mocha-multi-reporters --reporter-options configFile=reporter-config.json
      - name: Copy test execution videos
        working-directory: ui-test
        run: |
          mkdir public
          cp -r /__w/test/test/ui-test/cypress/videos/ public/videos/

