name: Cypress - PR Run

on:
  push:

jobs:
  identify-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # path: 'test/ui-test/cypress/support/page_objects'

      - name: Verify Remote Branch
        run: git branch -a

      - name: Fetch Main Branch
        run: git fetch origin master:refs/remotes/origin/master

      - name: Identify modified support folders
        id: identify-folders
        run: |
          changed_files=$(git diff --name-only remotes/origin/master "${GITHUB_HEAD_REF}")
          echo "::set-output name=files::${changed_files}"
