name: Identify Modified Support Folders

on:
  pull_request:
    paths:
      - 'ui-test/**'

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        id: set-files
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})

          # Debugging: Print the value of changed_files to the console
          echo "Changed files: $changed_files"

          # Append multi-line content to a file using the list of changed files
          echo 'RESULT<<EOF' >> $GITHUB_ENV
          for file in $changed_files; do
            echo "$file"
          done >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

  display-changed-files:
    needs: identify-folders
    runs-on: ubuntu-latest

    steps:
      - name: Display Changed Files
        run: |
          echo "Changed files:"
          cat $GITHUB_ENV
        working-directory: ${{ github.workspace }}
