name: Identify Modified Support Folders

on: push

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})

          # Set an environment variable with the list of changed files
          echo "CHANGED_FILES=${changed_files}" >> $GITHUB_ENV

  display-changed-files:
    needs: identify-folders
    runs-on: ubuntu-latest

    steps:
      - name: Display Changed Files
        run: |
          echo "Changed files: $CHANGED_FILES"
        working-directory: ui-test