name: Identify Modified Support Folders

on: push

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Main Branch
        run: git checkout master

      - name: Get Changed Files
        id: changed_files
        run: |
          # Use git commands or GitHub API to get the list of changed files
          changed_files=$(git diff --name-only origin/main...HEAD)
          echo "::set-output name=files::${changed_files}"

      - name: Run Cypress Tests
        run: |
          # Install dependencies and run Cypress tests
          npm install
          npx cypress run --spec "${{ steps.changed_files.outputs.files }}"
