name: Identify Modified Support Folders

on:
  pull_request:
    branches:
      - '*'

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Identify Modified Support Folders
        id: identify-folders
        run: |
          # Ensure we have the latest from the remote
          git fetch origin

          # Identify changed files between master and the pull request branch
          changed_files=$(git diff --name-only origin/master "${GITHUB_HEAD_REF}")

          # Set the output variable for further use
          echo "::set-output name=files::${changed_files}"

      - name: Display Changed Files
        run: |
         echo "Changed files: ${{ steps.identify-folders.outputs.files }}"
