name: Identify Modified Support Folders

on: push

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})
      
          # Initialize an array to store JS files
          js_files=()
      
          # Loop through each changed file
          for file in $changed_files; do
            # Check if the file has a ".js" extension
            if [[ $file == *.js ]]; then
              # Append the file to the array
              js_files+=("$file")
            fi
          done
      
          # Set an environment variable with the list of changed JS files
          echo "CHANGED_JS_FILES='${js_files[@]}'" >> $GITHUB_ENV

  display-changed-files:
    needs: identify-folders
    runs-on: ubuntu-latest

    steps:
      - name: Display Changed Files
        run: |
          echo "Changed files: $CHANGED_FILES"
        working-directory: ui-test