name: Identify Modified Support Folders

on: push

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    outputs:
      files: ${{ steps.set-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        id: set-files
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})

          # Debugging: Print the value of changed_files to the console
          echo "Changed files: $changed_files"

          # Set an environment variable with the list of changed files
          echo 'changed_files<<EOF' >> $GITHUB_OUTPUT
          echo $multiLine >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT"

  display-changed-files:
    needs: identify-folders
    runs-on: ubuntu-latest

    steps:
      - name: Display Changed Files
        run: |
          echo "Changed files: ${{ needs.identify-folders.outputs.files }}"
        working-directory: ${{ github.workspace }}
