name: Build Cypress File Paths

on:
  push:
    branches:
      - main

jobs:
  build_cypress_file_paths:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract JS files
        id: extract_js
        run: |
          # Get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Use grep and sed to filter out .cy.js files and extract .js files
          js_files=($(echo "$changed_files" | grep -E '\.js$' | grep -vE '\.cy\.js$' | sed 's|.*/\([^/]*\.js\)|\1|'))

          # Concatenate JS files into a single line
          js_files_concatenated=$(IFS=" " ; echo "${js_files[*]}")

          echo "Changed JS files:"
          echo "$js_files_concatenated"

          # Set environment variable for JS files
          echo "JS_FILES=$js_files_concatenated" >> $GITHUB_ENV

      - name: Build Cypress file paths
        id: build_cypress_paths
        run: |
          # Access environment variable to build Cypress file paths
          cypress_paths=""
          for js_file in $JS_FILES; do
            cypress_path="./${js_file%.*}/**.cy.js"
            cypress_paths="$cypress_paths $cypress_path"
          done

          echo "Cypress file paths:"
          echo "$cypress_paths"

          # Set environment variable for Cypress file paths
          echo "CYPRESS_PATHS=$cypress_paths" >> $GITHUB_ENV

      - name: Set environment variable
        run: echo "MY_ENV_VARIABLE=\"$CYPRESS_PATHS\"" >> $GITHUB_ENV

      - name: Use Cypress file paths
        run: |
          # Access environment variable for Cypress file paths in another step
          echo "Using Cypress file paths: $MY_ENV_VARIABLE"