name: Identify Modified Support Folders

on: push

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:

      - name: Print current directory
        run: |
          echo "Current directory: $PWD"
          ls   # List the contents of the current directory


      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: bean
      
      - name: Extract JS files
        id: extract_js
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')

          # Debugging: Print the value of changed_files to the console
          echo "Changed files: $changed_files"

          js_files=$(echo "$changed_files" | tr ' ' '\n' | grep -E '\.js$' | grep -vE '\.cy\.js$' | sed 's|.*/\([^/]*\)\.js|\1|' | tr '\n' ' ')

          echo "filtered files: $js_files"

          # Save the multi-line content to an environment variable
          echo "CHANGED_FILES=$js_files" >> $GITHUB_ENV

      - name: Use the environment variable in another step
        run: |
          # Access the environment variable in another step
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Build Cypress file paths
        id: build_cypress_paths
        run: |
            # Split CHANGED_FILES string into an array
            IFS=' ' read -ra files_array <<< "$CHANGED_FILES"
        
            # Access environment variable to build Cypress file paths
            cypress_paths=""
            for file_path in "${files_array[@]}"; do
              cypress_path="./${file_path%.*}/**/*.cy.js"
              cypress_paths="$cypress_paths \"$cypress_path\""
            done
        
            echo "Cypress file paths:"
            echo "$cypress_paths"
        
            # Set environment variable for Cypress file paths
            echo "CYPRESS_PATHS=$cypress_paths" >> $GITHUB_ENV
            

      - name: Use Cypress file paths
        run: |
          # Access environment variable for Cypress file paths in another step
          echo "Using Cypress file paths: $CYPRESS_PATHS"
