name: Identify Modified Support Folders

on:
  pull_request:
    paths:
      - 'ui-test/**'

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    outputs:
      id: identify-folders
      value: ${{ steps.set-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        id: set-files
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})

          # Set the output variable for further use
          echo "::set-output name=files::${changed_files}"

  display-changed-files:
    needs: identify-folders
    runs-on: ubuntu-latest

    steps:
      - name: Display Changed Files
        run: |
          echo "Changed files: ${{ needs.identify-folders.outputs.files }}"
        working-directory: ui-test