name: Identify Modified Support Folders

on: push

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Identify Modified Support Folders
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/master ${{ github.event.before }} ${{ github.sha }})

          # Debugging: Print the value of changed_files to the console
          echo "Changed files: $changed_files"

          # Append multi-line content to a file using the list of changed files
          echo 'Changed files:' >> $GITHUB_ENV
          for file in $changed_files; do
            echo "$file"
          done >> $GITHUB_ENV

          # Display the content
          cat $GITHUB_ENV