name: Identify Modified Support Folders

on: push
  

jobs:
  identify-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.before }} # This ensures that we fetch the full history

      - name: Identify Modified Support Folders
        id: identify-folders
        run: |
          # Identify changed files between main and the push commit
          changed_files=$(git diff --name-only origin/main ${{ github.event.before }} ${{ github.sha }})

          # Set the output variable for further use
          echo "::set-output name=files::${changed_files}"

      - name: Display Changed Files
        run: |
         echo "Changed files: ${{ steps.identify-folders.outputs.files }}"
