# action.yml
name: Send Report Links
on: 
    schedule:
      - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}